import{initializeApp}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import{getAuth,onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,updateProfile,signOut}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import{getFirestore,collection,addDoc,setDoc,doc,getDoc,getDocs,query,where,orderBy,limit,startAfter,serverTimestamp,increment,updateDoc,onSnapshot}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import{firebaseConfig}from"./firebase-config.js";

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
let user=null,userProfile=null,jobs=[],lastDoc=null,stopEmployerJobs=null,pageSize=12,logoDataUrl="";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const safe=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const money=n=>new Intl.NumberFormat("th-TH").format(Number(n)||0);
const salary=j=>j.salaryMin||j.salaryMax?`${j.salaryMin?money(j.salaryMin):"ไม่ระบุ"} – ${j.salaryMax?money(j.salaryMax):"ไม่ระบุ"} บาท`:"ตามตกลง";
const toast=m=>{const e=$("#toast");if(!e)return;e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2600)};
const errorText=e=>{const m=e?.code||e?.message||"";if(m.includes("email-already"))return"อีเมลนี้มีบัญชีแล้ว";if(m.includes("invalid-credential"))return"อีเมลหรือรหัสผ่านไม่ถูกต้อง";if(m.includes("weak-password"))return"รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร";if(m.includes("permission-denied"))return"ไม่มีสิทธิ์ทำรายการนี้ กรุณาตรวจสอบบัญชี";return e?.message||"เกิดข้อผิดพลาด กรุณาลองใหม่"};

function openDialog(id){const d=$(id);if(d&&!d.open)d.showModal()}
function closeDialogs(){["#authDialog","#jobDialog","#postDialog"].forEach(id=>{const d=$(id);if(d?.open)d.close()})}
$$('[data-close]').forEach(b=>b.onclick=closeDialogs);
$("#menuBtn").onclick=()=>$("#nav").classList.toggle("open");
async function loadProfile(){if(!auth.currentUser)return null;const s=await getDoc(doc(db,"users",auth.currentUser.uid));return s.exists()?s.data():null}
function isActive(){return userProfile?.status!=="suspended"}
function selectPortal(role){document.body.classList.remove("portal-candidate","portal-employer");document.body.classList.add("portal-"+role);location.hash=role==="candidate"?"jobs":"employer";window.scrollTo({top:0,behavior:"smooth"})}

async function loadJobs(reset=true){try{if(reset){jobs=[];lastDoc=null}let q=query(collection(db,"jobs"),where("status","==","published"),orderBy("publishedAt","desc"),limit(pageSize));if(lastDoc)q=query(collection(db,"jobs"),where("status","==","published"),orderBy("publishedAt","desc"),startAfter(lastDoc),limit(pageSize));const snap=await getDocs(q);lastDoc=snap.docs.at(-1)||lastDoc;jobs.push(...snap.docs.map(d=>({id:d.id,...d.data()})));renderJobs();$("#jobStat").textContent=jobs.length+(snap.size===pageSize?"+":"")}catch(e){console.error(e);$("#jobsGrid").innerHTML='<div class="empty">ยังไม่พบงานที่เผยแพร่ หรือกำลังรอการตั้งค่า Firestore Index</div>'}}
function filteredJobs(){const k=$("#jobSearch").value.trim().toLowerCase(),c=$("#categoryFilter").value,t=$("#typeFilter").value,l=$("#locationFilter").value.trim().toLowerCase();return jobs.filter(j=>(!k||`${j.title||""} ${j.companyName||""} ${j.skills||""}`.toLowerCase().includes(k))&&(!c||j.category===c)&&(!t||j.type===t)&&(!l||`${j.province||""} ${j.district||""}`.toLowerCase().includes(l)))}
function jobLogo(j){return j.companyLogo?`<img src="${safe(j.companyLogo)}" alt="โลโก้ ${safe(j.companyName)}" style="width:52px;height:52px;border-radius:12px;object-fit:cover;border:1px solid #dbe5ee">`:''}
function renderJobs(){const list=filteredJobs(),box=$("#jobsGrid");if(!list.length){box.innerHTML='<div class="empty">ไม่พบตำแหน่งงานตามเงื่อนไข ลองเปลี่ยนคำค้นหาหรือตัวกรอง</div>';return}box.innerHTML=list.map(j=>`<article class="job-card"><header><span class="badge">${safe(j.category)}</span><span class="verified">${j.companyVerified?'✓ ยืนยันแล้ว':''}</span></header><div style="display:flex;gap:12px;align-items:center;margin-top:10px">${jobLogo(j)}<div><h3 style="margin:0 0 4px">${safe(j.title)}</h3><div class="company">${safe(j.companyName)}</div></div></div><div class="salary">${salary(j)}</div><div class="meta">⌖ ${safe(j.district?j.district+", ":"")}${safe(j.province)}</div><div class="meta">▣ ${safe(j.type)}${j.vacancies?` · รับ ${safe(j.vacancies)} อัตรา`:''}</div><div class="card-actions"><button class="btn primary" data-view="${j.id}">ดูรายละเอียด</button><button class="btn ghost save" data-save="${j.id}">♡</button></div></article>`).join("");$$('[data-view]').forEach(b=>b.onclick=()=>showJob(b.dataset.view));$$('[data-save]').forEach(b=>b.onclick=()=>saveJob(b.dataset.save))}
function contactHtml(j){const items=[];if(j.contactPhone)items.push(`โทร: ${safe(j.contactPhone)}`);if(j.contactEmail)items.push(`อีเมล: ${safe(j.contactEmail)}`);if(j.lineId)items.push(`LINE: ${safe(j.lineId)}`);if(j.companyWebsite)items.push(`เว็บไซต์: ${safe(j.companyWebsite)}`);if(j.facebookUrl)items.push(`Facebook: ${safe(j.facebookUrl)}`);if(j.linkedinUrl)items.push(`LinkedIn: ${safe(j.linkedinUrl)}`);if(j.socialUrl)items.push(`Social: ${safe(j.socialUrl)}`);return items.length?`<h3>ช่องทางการติดต่อ</h3><p>${items.join('<br>')}</p>`:''}
async function showJob(id){const j=jobs.find(x=>x.id===id);if(!j)return;$("#jobDetail").innerHTML=`<div style="display:flex;gap:14px;align-items:center">${jobLogo(j)}<div><span class="badge">${safe(j.category)}</span><h2 style="margin:6px 0">${safe(j.title)}</h2><p class="company">${safe(j.companyName)} ${j.companyVerified?'<span class="verified">✓ บริษัทผ่านการตรวจสอบ</span>':''}</p></div></div><h3>${salary(j)}</h3><p>⌖ ${safe(j.district?j.district+", ":"")}${safe(j.province)} · ${safe(j.type)}${j.vacancies?` · รับ ${safe(j.vacancies)} อัตรา`:''}</p>${j.experience?`<p>ประสบการณ์: ${safe(j.experience)}</p>`:''}${j.education?`<p>การศึกษา: ${safe(j.education)}</p>`:''}<hr><h3>รายละเอียดงาน</h3><p>${safe(j.description).replace(/\n/g,"<br>")}</p><h3>คุณสมบัติ</h3><p>${safe(j.requirements).replace(/\n/g,"<br>")}</p>${j.skills?`<h3>ทักษะที่ต้องการ</h3><p>${safe(j.skills)}</p>`:''}${j.benefits?`<h3>สวัสดิการ</h3><p>${safe(j.benefits).replace(/\n/g,"<br>")}</p>`:""}${contactHtml(j)}<button class="btn primary wide" id="applyBtn">สมัครงานนี้</button><button class="text-btn" id="reportBtn">รายงานประกาศนี้</button>`;openDialog("#jobDialog");$("#applyBtn").onclick=()=>applyJob(j);$("#reportBtn").onclick=()=>reportJob(j.id);updateDoc(doc(db,"jobs",id),{viewCount:increment(1)}).catch(()=>{})}

async function requireCandidate(){if(!user){openAuth("candidate","login");return false}if(!isActive()){toast("บัญชีนี้ถูกระงับการใช้งาน");return false}if(userProfile?.role!=="candidate"){toast("ฟังก์ชันนี้สำหรับบัญชีผู้หางาน");return false}return true}
async function applyJob(j){if(!await requireCandidate())return;try{await setDoc(doc(db,"applications",`${j.id}_${user.uid}`),{jobId:j.id,jobTitle:j.title,companyId:j.employerId,companyName:j.companyName,candidateId:user.uid,candidateName:user.displayName||userProfile.displayName,status:"submitted",createdAt:serverTimestamp(),updatedAt:serverTimestamp()});closeDialogs();toast("ส่งใบสมัครเรียบร้อยแล้ว")}catch(e){toast(errorText(e))}}
async function saveJob(id){if(!await requireCandidate())return;try{await setDoc(doc(db,"users",user.uid,"savedJobs",id),{jobId:id,createdAt:serverTimestamp()});toast("บันทึกงานแล้ว")}catch(e){toast(errorText(e))}}
async function reportJob(id){if(!user){openAuth("candidate","login");return}if(!isActive())return toast("บัญชีนี้ถูกระงับการใช้งาน");try{await addDoc(collection(db,"reports"),{jobId:id,reporterId:user.uid,reason:"ผู้ใช้ขอตรวจสอบประกาศ",status:"open",createdAt:serverTimestamp()});closeDialogs();toast("รับรายงานแล้ว ทีมงานจะตรวจสอบ")}catch(e){toast(errorText(e))}}

function openAuth(role="candidate",mode="login"){$("#authChoice").classList.add("hidden");$("#authForm").classList.remove("hidden");$("#authRole").value=role;$("#authMode").value=mode;const reg=mode==="register";$("#accountType").textContent=role==="employer"?"บัญชีนายจ้าง":"บัญชีผู้หางาน";$("#authTitle").textContent=reg?(role==="employer"?"สมัครบัญชีนายจ้าง":"สมัครบัญชีผู้หางาน"):(role==="employer"?"เข้าสู่ระบบนายจ้าง":"เข้าสู่ระบบผู้หางาน");$("#displayName").parentElement.classList.toggle("hidden",!reg);$("#consentRow").classList.toggle("hidden",!reg);$("#toggleAuth").textContent=reg?"มีบัญชีแล้ว? เข้าสู่ระบบ":"ยังไม่มีบัญชี? สมัครสมาชิก";openDialog("#authDialog")}
$$('[data-auth-role]').forEach(b=>b.onclick=async()=>{const role=b.dataset.authRole;if(userProfile?.role==="admin")return location.href="admin.html";if(user&&userProfile?.role===role&&isActive())return selectPortal(role);openAuth(role,"login")});
$$('[data-register]').forEach(b=>b.onclick=()=>openAuth(b.dataset.register,"register"));
$$('[data-role]').forEach(b=>b.onclick=()=>openAuth(b.dataset.role,"register"));
$("#showLogin").onclick=()=>openAuth("candidate","login");
$("#toggleAuth").onclick=()=>openAuth($("#authRole").value,$("#authMode").value==="login"?"register":"login");

$("#authForm").onsubmit=async e=>{e.preventDefault();const mode=$("#authMode").value,role=$("#authRole").value,email=$("#email").value.trim(),password=$("#password").value,name=$("#displayName").value.trim();$("#authError").textContent="";try{if(mode==="register"){if(!name)throw new Error("กรุณากรอกชื่อ");if(!$("#consent").checked)throw new Error("กรุณายอมรับเงื่อนไขการใช้งาน");const cred=await createUserWithEmailAndPassword(auth,email,password);await updateProfile(cred.user,{displayName:name});const profile={displayName:name,email,role,status:"active",profileVisibility:role==="candidate"?"private":"public",companyVerified:false,createdAt:serverTimestamp(),updatedAt:serverTimestamp()};await setDoc(doc(db,"users",cred.user.uid),profile);if(role==="employer")await setDoc(doc(db,"companies",cred.user.uid),{name,contactEmail:email,verified:false,status:"active",createdAt:serverTimestamp(),updatedAt:serverTimestamp()});user=cred.user;userProfile=profile}else{const cred=await signInWithEmailAndPassword(auth,email,password);user=cred.user;userProfile=await loadProfile();if(!userProfile)throw new Error("ไม่พบข้อมูลบัญชี กรุณาติดต่อผู้ดูแล");if(userProfile.status==="suspended"){await signOut(auth);throw new Error("บัญชีนี้ถูกระงับการใช้งาน กรุณาติดต่อผู้ดูแล")};if(userProfile.role==="admin"){closeDialogs();location.href="admin.html";return}if(userProfile.role!==role){await signOut(auth);throw new Error(role==="employer"?"บัญชีนี้เป็นบัญชีผู้หางาน กรุณาเข้าทางผู้หางาน":"บัญชีนี้เป็นบัญชีนายจ้าง กรุณาเข้าทางนายจ้าง")}}closeDialogs();watchEmployerJobs();selectPortal(role);toast(mode==="register"?"สร้างบัญชีสำเร็จ":"เข้าสู่ระบบสำเร็จ")}catch(err){$("#authError").textContent=errorText(err)}};

function watchEmployerJobs(){if(stopEmployerJobs){stopEmployerJobs();stopEmployerJobs=null}const allowed=user&&userProfile?.role==="employer"&&isActive();$("#employerDashboard").classList.toggle("hidden",!allowed);$("#employerSignup").classList.toggle("hidden",!!allowed);$("#employerJobs").replaceChildren();$("#employerJobsMessage").textContent="";if(!allowed)return;$("#employerJobsMessage").textContent="กำลังโหลดประกาศของคุณ…";stopEmployerJobs=onSnapshot(query(collection(db,"jobs"),where("employerId","==",user.uid)),snap=>{const list=snap.docs.map(d=>({...d.data(),id:d.id})).sort((a,b)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0));const labels={pending:"รอตรวจสอบ",published:"เผยแพร่แล้ว",rejected:"ไม่ผ่านการตรวจสอบ",closed:"ปิดรับสมัคร",draft:"ฉบับร่าง"};$("#employerJobsMessage").textContent=list.length?`ประกาศทั้งหมด ${list.length} รายการ`:"ยังไม่มีประกาศงาน กดลงประกาศงานเพื่อเริ่มต้น";$("#employerJobs").innerHTML=list.map(j=>`<article class="job-card"><div style="display:flex;gap:10px;align-items:center">${jobLogo(j)}<div><span class="badge">${safe(labels[j.status]||j.status)}</span><h3>${safe(j.title||'ยังไม่ระบุตำแหน่ง')}</h3><div class="company">${safe(j.companyName||'')}</div></div></div><div class="meta">${safe(j.province||'')} · ${safe(j.type||'')}</div>${j.status==="pending"?'<p class="notice">อยู่ระหว่างตรวจสอบ ยังไม่แสดงในหน้าค้นหางาน</p>':""}${j.status==="rejected"?`<p class="notice">เหตุผล: ${safe(j.rejectionReason||"กรุณาติดต่อผู้ดูแล")}</p><button class="btn ghost" data-resubmit="${j.id}">ส่งตรวจใหม่</button>`:""}</article>`).join("");$$('[data-resubmit]').forEach(b=>b.onclick=async()=>{try{await updateDoc(doc(db,"jobs",b.dataset.resubmit),{status:"pending",rejectionReason:"",updatedAt:serverTimestamp()});toast("ส่งประกาศเพื่อตรวจสอบใหม่แล้ว")}catch(e){toast(errorText(e))}})},e=>$("#employerJobsMessage").textContent="โหลดประกาศไม่สำเร็จ: "+errorText(e))}
$("#retryEmployerJobs").onclick=watchEmployerJobs;

onAuthStateChanged(auth,async u=>{user=u;userProfile=null;watchEmployerJobs();if(u){userProfile=await loadProfile();if(!userProfile)return;watchEmployerJobs();const employer=userProfile.role==="employer";$("#candidateEntry").classList.toggle("hidden",employer||userProfile.role==="admin");$("#employerEntry").classList.toggle("hidden",userProfile.role==="candidate");$("#candidateEntry").textContent="บัญชีผู้หางาน";$("#employerEntry").textContent=userProfile.role==="admin"?"ผู้ดูแลระบบ":"บัญชีนายจ้าง";$("#logoutBtn").classList.remove("hidden");if(userProfile.role==="employer")prefillEmployerForm()}else{$("#candidateEntry").classList.remove("hidden");$("#employerEntry").classList.remove("hidden");$("#candidateEntry").textContent="ผู้หางาน";$("#employerEntry").textContent="นายจ้าง / ลงประกาศ";$("#logoutBtn").classList.add("hidden")}});
$("#logoutBtn").onclick=async()=>{await signOut(auth);toast("ออกจากระบบแล้ว")};

async function prefillEmployerForm(){const f=$("#postForm");if(!f||!user)return;try{const c=await getDoc(doc(db,"companies",user.uid));const d=c.exists()?c.data():{};const values={companyName:d.name||userProfile?.displayName||"",industry:d.industry||"",companySize:d.companySize||"",companyWebsite:d.companyWebsite||"",contactEmail:d.contactEmail||userProfile?.email||user?.email||"",contactPhone:d.contactPhone||"",lineId:d.lineId||"",facebookUrl:d.facebookUrl||"",linkedinUrl:d.linkedinUrl||"",socialUrl:d.socialUrl||""};Object.entries(values).forEach(([k,v])=>{if(f.elements[k]&&!f.elements[k].value)f.elements[k].value=v})}catch(e){console.warn(e)}}
$$('[data-post-job]').forEach(b=>b.onclick=async()=>{if(!user)return openAuth("employer","login");if(userProfile?.role!=="employer")return toast("กรุณาใช้บัญชีนายจ้าง");await prefillEmployerForm();openDialog("#postDialog")});

const logoInput=$("#companyLogo"),logoPreview=$("#logoPreview");if(logoInput)logoInput.onchange=()=>{const file=logoInput.files?.[0];logoDataUrl="";if(!file)return;if(file.size>1024*1024){toast("โลโก้ต้องมีขนาดไม่เกิน 1 MB");logoInput.value="";return}const reader=new FileReader();reader.onload=()=>{logoDataUrl=String(reader.result||"");logoPreview.innerHTML=`<img src="${logoDataUrl}" alt="ตัวอย่างโลโก้">`};reader.readAsDataURL(file)};

function formToObject(f){const data=Object.fromEntries(new FormData(f));delete data.companyLogo;data.salaryMin=Number(data.salaryMin)||0;data.salaryMax=Number(data.salaryMax)||0;data.vacancies=Number(data.vacancies)||1;return data}
async function saveCompanyProfile(data){if(!user)return;const patch={name:data.companyName||userProfile?.displayName||"",industry:data.industry||"",companySize:data.companySize||"",companyWebsite:data.companyWebsite||"",contactEmail:data.contactEmail||"",contactPhone:data.contactPhone||"",lineId:data.lineId||"",facebookUrl:data.facebookUrl||"",linkedinUrl:data.linkedinUrl||"",socialUrl:data.socialUrl||"",updatedAt:serverTimestamp()};await setDoc(doc(db,"companies",user.uid),patch,{merge:true})}
$("#postForm").onsubmit=async e=>{e.preventDefault();if(!user||userProfile?.role!=="employer")return openAuth("employer","login");const f=formToObject(e.target);try{await saveCompanyProfile(f);await addDoc(collection(db,"jobs"),{...f,companyLogo:logoDataUrl||"",employerId:user.uid,status:"pending",companyVerified:!!userProfile.companyVerified,viewCount:0,applicationCount:0,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});e.target.reset();logoDataUrl="";if(logoPreview)logoPreview.textContent="LOGO";closeDialogs();selectPortal("employer");watchEmployerJobs();toast("ส่งประกาศแล้ว อยู่ระหว่างตรวจสอบ")}catch(err){$("#postMessage").textContent=errorText(err)}};
const saveDraftBtn=$("#saveDraftBtn");if(saveDraftBtn)saveDraftBtn.onclick=async()=>{if(!user||userProfile?.role!=="employer")return openAuth("employer","login");const f=formToObject($("#postForm"));if(!f.title&&!f.companyName)return toast("กรอกชื่อบริษัทหรือตำแหน่งก่อนบันทึก");try{await saveCompanyProfile(f);await addDoc(collection(db,"jobs"),{...f,companyLogo:logoDataUrl||"",employerId:user.uid,status:"draft",companyVerified:!!userProfile.companyVerified,viewCount:0,applicationCount:0,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});closeDialogs();watchEmployerJobs();toast("บันทึกฉบับร่างแล้ว")}catch(e){toast(errorText(e))}};

[$("#jobSearch"),$("#categoryFilter"),$("#typeFilter"),$("#locationFilter")].forEach(e=>e.oninput=renderJobs);$("#resetFilters").onclick=()=>{[$("#jobSearch"),$("#categoryFilter"),$("#typeFilter"),$("#locationFilter")].forEach(e=>e.value="");renderJobs()};$("#loadMore").onclick=()=>loadJobs(false);$("#heroSearch").onsubmit=e=>{e.preventDefault();$("#jobSearch").value=$("#heroKeyword").value;$("#locationFilter").value=$("#heroLocation").value;location.hash="jobs";renderJobs()};$$('[data-keyword]').forEach(b=>b.onclick=()=>{$("#heroKeyword").value=b.dataset.keyword;$("#heroSearch").requestSubmit()});
async function loadCompanies(){try{const s=await getDocs(query(collection(db,"companies"),where("verified","==",true),limit(8)));$("#companyStat").textContent=s.size;const box=$("#companyGrid");if(s.empty)return;box.innerHTML=s.docs.map(d=>{const c=d.data();return`<article class="company-card"><span class="verified">✓ ผ่านการตรวจสอบ</span><h3>${safe(c.name)}</h3><p>${safe(c.industry||"")} · ${safe(c.province||"")}</p></article>`}).join("")}catch(e){console.warn(e)}}
$("#privacyBtn").onclick=()=>alert("WebHub Jobs ใช้ข้อมูลเพื่อให้บริการหางานและสรรหาบุคลากร ผู้สมัครกำหนดการมองเห็นโปรไฟล์ได้ และสามารถขอลบข้อมูลได้ทาง support@webhub.asia");loadJobs();loadCompanies();