import{initializeApp}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import{getAuth,onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,updateProfile,signOut}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import{getFirestore,collection,addDoc,setDoc,doc,getDoc,getDocs,query,where,orderBy,limit,startAfter,serverTimestamp,increment,updateDoc}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import{firebaseConfig}from"./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);let user=null,userProfile=null,jobs=[],lastDoc=null,pageSize=12;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const safe=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const toast=m=>{const e=$("#toast");e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2600)};
const money=n=>new Intl.NumberFormat("th-TH").format(Number(n)||0);
const formatSalary=j=>j.salaryMin||j.salaryMax?`${j.salaryMin?money(j.salaryMin):"ไม่ระบุ"} – ${j.salaryMax?money(j.salaryMax):"ไม่ระบุ"} บาท`:"ตามตกลง";
function openDialog(id){const d=$(id);if(!d.open)d.showModal()} function closeDialogs(){[$("#authDialog"),$("#jobDialog"),$("#postDialog")].forEach(x=>x.open&&x.close())}
$$('[data-close]').forEach(b=>b.onclick=closeDialogs);$("#menuBtn").onclick=()=>$("#nav").classList.toggle("open");

async function loadJobs(reset=true){try{if(reset){jobs=[];lastDoc=null}let q=query(collection(db,"jobs"),where("status","==","published"),orderBy("publishedAt","desc"),limit(pageSize));if(lastDoc)q=query(collection(db,"jobs"),where("status","==","published"),orderBy("publishedAt","desc"),startAfter(lastDoc),limit(pageSize));const snap=await getDocs(q);lastDoc=snap.docs.at(-1)||lastDoc;jobs.push(...snap.docs.map(d=>({id:d.id,...d.data()})));renderJobs();$("#jobStat").textContent=jobs.length+(snap.size===pageSize?"+":"")}catch(e){console.error(e);$("#jobsGrid").innerHTML='<div class="empty">ยังไม่พบงานที่เผยแพร่ หรือกำลังรอการตั้งค่า Firestore Index</div>'}}
function filteredJobs(){const k=$("#jobSearch").value.trim().toLowerCase(),c=$("#categoryFilter").value,t=$("#typeFilter").value,l=$("#locationFilter").value.trim().toLowerCase();return jobs.filter(j=>(!k||`${j.title} ${j.companyName} ${j.skills||""}`.toLowerCase().includes(k))&&(!c||j.category===c)&&(!t||j.type===t)&&(!l||`${j.province} ${j.district||""}`.toLowerCase().includes(l)))}
function renderJobs(){const list=filteredJobs(),box=$("#jobsGrid");if(!list.length){box.innerHTML='<div class="empty">ไม่พบตำแหน่งงานตามเงื่อนไข ลองเปลี่ยนคำค้นหาหรือตัวกรอง</div>';return}box.innerHTML=list.map(j=>`<article class="job-card"><header><span class="badge">${safe(j.category)}</span><span class="verified">${j.companyVerified?'✓ ยืนยันแล้ว':''}</span></header><h3>${safe(j.title)}</h3><div class="company">${safe(j.companyName)}</div><div class="salary">${formatSalary(j)}</div><div class="meta">⌖ ${safe(j.district?j.district+", ":"")}${safe(j.province)}</div><div class="meta">▣ ${safe(j.type)}</div><div class="card-actions"><button class="btn primary" data-view="${j.id}">ดูรายละเอียด</button><button class="btn ghost save" data-save="${j.id}" aria-label="บันทึกงาน">♡</button></div></article>`).join("");$$('[data-view]').forEach(b=>b.onclick=()=>showJob(b.dataset.view));$$('[data-save]').forEach(b=>b.onclick=()=>saveJob(b.dataset.save))}
[$("#jobSearch"),$("#categoryFilter"),$("#typeFilter"),$("#locationFilter")].forEach(e=>e.oninput=renderJobs);$("#resetFilters").onclick=()=>{[$("#jobSearch"),$("#categoryFilter"),$("#typeFilter"),$("#locationFilter")].forEach(e=>e.value="");renderJobs()};$("#loadMore").onclick=()=>loadJobs(false);
$("#heroSearch").onsubmit=e=>{e.preventDefault();$("#jobSearch").value=$("#heroKeyword").value;$("#locationFilter").value=$("#heroLocation").value;location.hash="jobs";renderJobs()};$$('[data-keyword]').forEach(b=>b.onclick=()=>{$("#heroKeyword").value=b.dataset.keyword;$("#heroSearch").requestSubmit()});
async function showJob(id){const j=jobs.find(x=>x.id===id);if(!j)return;$("#jobDetail").innerHTML=`<span class="badge">${safe(j.category)}</span><h2>${safe(j.title)}</h2><p class="company">${safe(j.companyName)} ${j.companyVerified?'<span class="verified">✓ บริษัทผ่านการตรวจสอบ</span>':''}</p><h3>${formatSalary(j)}</h3><p>⌖ ${safe(j.district?j.district+", ":"")}${safe(j.province)} · ${safe(j.type)}</p><hr><h3>รายละเอียดงาน</h3><p>${safe(j.description).replace(/\n/g,"<br>")}</p><h3>คุณสมบัติ</h3><p>${safe(j.requirements).replace(/\n/g,"<br>")}</p>${j.benefits?`<h3>สวัสดิการ</h3><p>${safe(j.benefits).replace(/\n/g,"<br>")}</p>`:""}<button class="btn primary wide" id="applyBtn">สมัครงานนี้</button><button class="text-btn" id="reportBtn">รายงานประกาศนี้</button>`;openDialog("#jobDialog");$("#applyBtn").onclick=()=>applyJob(j);$("#reportBtn").onclick=()=>reportJob(j.id);updateDoc(doc(db,"jobs",id),{viewCount:increment(1)}).catch(()=>{})}
async function requireCandidate(){if(!user){openAuth("candidate","login");return false}if(userProfile?.role!=="candidate"){toast("ฟังก์ชันนี้สำหรับบัญชีผู้หางาน");return false}return true}
async function applyJob(j){if(!await requireCandidate())return;try{await setDoc(doc(db,"applications",`${j.id}_${user.uid}`),{jobId:j.id,jobTitle:j.title,companyId:j.employerId,companyName:j.companyName,candidateId:user.uid,candidateName:user.displayName||userProfile.displayName,status:"submitted",createdAt:serverTimestamp(),updatedAt:serverTimestamp()});closeDialogs();toast("ส่งใบสมัครเรียบร้อยแล้ว")}catch(e){toast(errorText(e))}}
async function saveJob(id){if(!await requireCandidate())return;try{await setDoc(doc(db,"users",user.uid,"savedJobs",id),{jobId:id,createdAt:serverTimestamp()});toast("บันทึกงานแล้ว")}catch(e){toast(errorText(e))}}
async function reportJob(id){if(!user){openAuth("candidate","login");return}try{await addDoc(collection(db,"reports"),{jobId:id,reporterId:user.uid,reason:"ผู้ใช้ขอตรวจสอบประกาศ",status:"open",createdAt:serverTimestamp()});closeDialogs();toast("รับรายงานแล้ว ทีมงานจะตรวจสอบ")}catch(e){toast(errorText(e))}}

function openAuth(role="candidate",mode="login"){$("#authChoice").classList.add("hidden");$("#authForm").classList.remove("hidden");$("#authRole").value=role;$("#authMode").value=mode;const reg=mode==="register";$("#accountType").textContent=role==="employer"?"บัญชีนายจ้าง":"บัญชีผู้หางาน";$("#authTitle").textContent=reg?(role==="employer"?"สมัครบัญชีนายจ้าง":"สมัครบัญชีผู้หางาน"):(role==="employer"?"เข้าสู่ระบบนายจ้าง":"เข้าสู่ระบบผู้หางาน");$("#displayName").parentElement.classList.toggle("hidden",!reg);$("#consentRow").classList.toggle("hidden",!reg);$("#toggleAuth").textContent=reg?"มีบัญชีแล้ว? เข้าสู่ระบบ":"ยังไม่มีบัญชี? สมัครสมาชิก";openDialog("#authDialog")}
function selectPortal(role){document.body.classList.remove("portal-candidate","portal-employer");document.body.classList.add("portal-"+role);location.hash=role==="candidate"?"jobs":"talent";window.scrollTo({top:0,behavior:"smooth"})}$$(`[data-auth-role]`).forEach(b=>b.onclick=()=>{const role=b.dataset.authRole;selectPortal(role);const valid=userProfile&&(userProfile.role===role||(role==="employer"&&userProfile.role==="admin"));if(!valid)openAuth(role,"login")});$$('[data-register]').forEach(b=>b.onclick=()=>openAuth(b.dataset.register,"register"));$$('[data-role]').forEach(b=>b.onclick=()=>openAuth(b.dataset.role,"register"));$("#showLogin").onclick=()=>openAuth("candidate","login");$("#toggleAuth").onclick=()=>openAuth($("#authRole").value,$("#authMode").value==="login"?"register":"login");
$("#authForm").onsubmit=async e=>{e.preventDefault();const mode=$("#authMode").value,role=$("#authRole").value,email=$("#email").value.trim(),password=$("#password").value,name=$("#displayName").value.trim();$("#authError").textContent="";try{if(mode==="register"){if(!name)throw new Error("กรุณากรอกชื่อ");if(!$("#consent").checked)throw new Error("กรุณายอมรับเงื่อนไขการใช้งาน");const cred=await createUserWithEmailAndPassword(auth,email,password);await updateProfile(cred.user,{displayName:name});const profile={displayName:name,email,role,status:"active",profileVisibility:role==="candidate"?"private":"public",createdAt:serverTimestamp(),updatedAt:serverTimestamp()};await setDoc(doc(db,"users",cred.user.uid),profile);user=cred.user;userProfile={...profile};}else{const cred=await signInWithEmailAndPassword(auth,email,password);const snap=await getDoc(doc(db,"users",cred.user.uid));user=cred.user;userProfile=snap.exists()?snap.data():null;const validRole=userProfile&&(userProfile.role===role||(role==="employer"&&userProfile.role==="admin"));if(!validRole){await signOut(auth);throw new Error(role==="employer"?"บัญชีนี้ไม่ใช่บัญชีนายจ้าง กรุณาเข้าทางผู้หางาน":"บัญชีนี้ไม่ใช่บัญชีผู้หางาน กรุณาเข้าทางนายจ้าง");}}closeDialogs();selectPortal(role);toast(mode==="register"?"สร้างบัญชีสำเร็จ":"เข้าสู่ระบบสำเร็จ")}catch(err){$("#authError").textContent=errorText(err)}};
function errorText(e){const m=e.code||e.message||"";if(m.includes("email-already"))return"อีเมลนี้มีบัญชีแล้ว";if(m.includes("invalid-credential"))return"อีเมลหรือรหัสผ่านไม่ถูกต้อง";if(m.includes("weak-password"))return"รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร";if(m.includes("permission-denied"))return"ไม่มีสิทธิ์ทำรายการนี้ กรุณาตรวจสอบบัญชี";return e.message||"เกิดข้อผิดพลาด กรุณาลองใหม่"}
onAuthStateChanged(auth,async u=>{user=u;userProfile=null;if(u){const snap=await getDoc(doc(db,"users",u.uid));userProfile=snap.exists()?snap.data():null;const employer=["employer","admin"].includes(userProfile?.role);$("#candidateEntry").classList.toggle("hidden",employer);$("#employerEntry").classList.toggle("hidden",!employer);$("#candidateEntry").textContent="บัญชีผู้หางาน";$("#employerEntry").textContent=userProfile?.role==="admin"?"ผู้ดูแลระบบ":"บัญชีนายจ้าง";$("#logoutBtn").classList.remove("hidden")}else{$("#candidateEntry").classList.remove("hidden");$("#employerEntry").classList.remove("hidden");$("#candidateEntry").textContent="ผู้หางาน";$("#employerEntry").textContent="นายจ้าง / ลงประกาศ";$("#logoutBtn").classList.add("hidden")}});$("#logoutBtn").onclick=async()=>{await signOut(auth);toast("ออกจากระบบแล้ว")};\n$$('[data-post-job]').forEach(b=>b.onclick=()=>{if(!user)return openAuth("employer","login");if(userProfile?.role!=="employer"&&userProfile?.role!=="admin")return toast("กรุณาใช้บัญชีนายจ้าง");openDialog("#postDialog")});
$("#postForm").onsubmit=async e=>{e.preventDefault();if(!user||!["employer","admin"].includes(userProfile?.role))return openAuth("employer","login");const f=Object.fromEntries(new FormData(e.target));f.salaryMin=Number(f.salaryMin)||0;f.salaryMax=Number(f.salaryMax)||0;try{await addDoc(collection(db,"jobs"),{...f,employerId:user.uid,status:"pending",companyVerified:!!userProfile.companyVerified,viewCount:0,applicationCount:0,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});e.target.reset();closeDialogs();toast("ส่งประกาศแล้ว อยู่ระหว่างตรวจสอบ")}catch(err){$("#postMessage").textContent=errorText(err)}};
async function loadCompanies(){try{const s=await getDocs(query(collection(db,"companies"),where("verified","==",true),limit(8)));$("#companyStat").textContent=s.size;const box=$("#companyGrid");if(s.empty)return;box.innerHTML=s.docs.map(d=>{const c=d.data();return`<article class="company-card"><span class="verified">✓ ผ่านการตรวจสอบ</span><h3>${safe(c.name)}</h3><p>${safe(c.industry||"")} · ${safe(c.province||"")}</p></article>`}).join("")}catch(e){console.warn(e)}}
$("#privacyBtn").onclick=()=>alert("WebHub Jobs ใช้ข้อมูลเพื่อให้บริการหางานและสรรหาบุคลากร ผู้สมัครกำหนดการมองเห็นโปรไฟล์ได้ และสามารถขอลบข้อมูลได้ทาง support@webhub.asia");loadJobs();loadCompanies();
