import{getApp}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import{getFirestore,doc,getDoc,setDoc,collection,query,where,onSnapshot,updateDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";

const app=getApp(),auth=getAuth(app),db=getFirestore(app);
const $=s=>document.querySelector(s);
let currentJobId="",currentJob=null,stopApps=null;
const safe=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const toast=m=>{const e=$("#toast");if(!e)return;e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2800)};
const dateText=t=>{try{return new Intl.DateTimeFormat("th-TH",{dateStyle:"medium",timeStyle:"short"}).format(t?.toDate?.()||new Date())}catch{return"-"}};

const css=document.createElement("style");css.textContent=`
#applicationDialog{width:min(760px,calc(100% - 24px));max-height:92vh;overflow:auto}
.apply-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;margin-bottom:18px}.apply-head h2{margin:4px 0}.apply-job{padding:12px 14px;border-radius:12px;background:#f0f9ff;color:#075985;font-weight:700}.apply-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.apply-grid label{display:block;font-size:13px;font-weight:700}.apply-grid input,.apply-grid select{width:100%;height:46px;margin-top:6px;border:1px solid #dbe5ee;border-radius:10px;padding:0 12px;background:#fff}.apply-note{margin:16px 0;padding:14px;border-radius:12px;background:#fffbeb;color:#92400e;font-size:13px;line-height:1.6}.apply-actions{display:flex;gap:10px;justify-content:flex-end;margin-top:18px}.review-box{border:1px solid #dbe5ee;border-radius:14px;overflow:hidden}.review-row{display:grid;grid-template-columns:160px 1fr;gap:10px;padding:11px 14px;border-bottom:1px solid #edf2f7}.review-row:last-child{border:0}.review-row b{color:#475569}.applicant-panel{grid-column:1/-1;margin-top:34px;padding-top:26px;border-top:1px solid rgba(255,255,255,.25)}.applicant-panel h2{color:#fff}.applicant-list{display:grid;gap:12px}.applicant-card{background:#fff;color:#0f172a;border-radius:16px;padding:18px}.applicant-card-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.applicant-card h3{margin:0 0 4px}.applicant-job{font-size:12px;color:#64748b}.applicant-info{display:grid;grid-template-columns:repeat(3,1fr);gap:8px 16px;margin:15px 0;font-size:13px}.applicant-info span{color:#64748b}.applicant-status{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.applicant-status select{height:40px;border:1px solid #dbe5ee;border-radius:9px;padding:0 10px;background:#fff}.resume-mail{display:inline-block;margin-top:8px;color:#0284c7;font-weight:700;text-decoration:none}
@media(max-width:650px){.apply-grid{grid-template-columns:1fr}.review-row{grid-template-columns:1fr;gap:2px}.applicant-info{grid-template-columns:1fr 1fr}.apply-actions{flex-direction:column-reverse}.apply-actions .btn{width:100%}}
`;document.head.appendChild(css);

const dialog=document.createElement("dialog");dialog.id="applicationDialog";dialog.innerHTML='<button class="close" id="closeApplication" type="button">×</button><div id="applicationContent"></div>';document.body.appendChild(dialog);
$("#closeApplication").onclick=()=>dialog.close();

async function userProfile(){const u=auth.currentUser;if(!u)return null;const s=await getDoc(doc(db,"users",u.uid));return s.exists()?s.data():null}
async function getJob(id){const s=await getDoc(doc(db,"jobs",id));return s.exists()?{id:s.id,...s.data()}:null}

async function openApplication(){
 const u=auth.currentUser;if(!u){toast("กรุณาเข้าสู่ระบบผู้หางานก่อนสมัคร");return}
 const p=await userProfile();if(!p||p.role!=="candidate"){toast("กรุณาใช้บัญชีผู้หางาน");return}if(p.status==="suspended"){toast("บัญชีนี้ถูกระงับการใช้งาน");return}
 currentJob=await getJob(currentJobId);if(!currentJob||currentJob.status!=="published"){toast("ไม่พบประกาศงานหรือประกาศปิดรับแล้ว");return}
 const content=$("#applicationContent");content.innerHTML=`<div class="apply-head"><div><span class="account-type">ใบสมัครงาน</span><h2>กรอกข้อมูลผู้สมัคร</h2><p>ข้อมูลนี้จะถูกส่งตรงไปยังนายจ้างของตำแหน่งนี้</p></div></div><div class="apply-job">${safe(currentJob.title)} · ${safe(currentJob.companyName)}</div><form id="applicationForm"><div class="apply-grid"><label>ชื่อ-นามสกุล *<input name="candidateName" required value="${safe(p.displayName||u.displayName||"")}"></label><label>เบอร์โทรศัพท์ *<input name="phone" required inputmode="tel" placeholder="เช่น 081-234-5678" value="${safe(p.phone||"")}"></label><label>อีเมล *<input name="email" type="email" required value="${safe(p.email||u.email||"")}"></label><label>อายุ *<input name="age" type="number" min="15" max="80" required placeholder="เช่น 28"></label><label>ประสบการณ์ *<select name="experience" required><option value="">เลือกประสบการณ์</option><option>ไม่มีประสบการณ์</option><option>น้อยกว่า 1 ปี</option><option>1-3 ปี</option><option>3-5 ปี</option><option>5-10 ปี</option><option>มากกว่า 10 ปี</option></select></label><label>การศึกษา *<select name="education" required><option value="">เลือกระดับการศึกษา</option><option>ต่ำกว่ามัธยมศึกษา</option><option>มัธยมศึกษา</option><option>ปวช.</option><option>ปวส.</option><option>ปริญญาตรี</option><option>ปริญญาโท</option><option>สูงกว่าปริญญาโท</option></select></label></div><div class="apply-note">Resume ไม่ต้องอัปโหลดในระบบ หลังจากยืนยันสมัครแล้ว กรุณาส่ง Resume แยกไปที่อีเมลนายจ้าง: <b>${safe(currentJob.contactEmail||"นายจ้างไม่ได้ระบุอีเมล")}</b></div><button class="btn primary wide" type="submit">ตรวจสอบข้อมูลก่อนสมัคร</button></form>`;
 $("#applicationForm").onsubmit=e=>{e.preventDefault();showReview(new FormData(e.target))};dialog.showModal();
}

function showReview(fd){const d=Object.fromEntries(fd);const c=$("#applicationContent");c.innerHTML=`<div class="apply-head"><div><span class="account-type">ตรวจสอบข้อมูล</span><h2>ยืนยันใบสมัคร</h2><p>ตรวจสอบข้อมูลให้ถูกต้องก่อนส่งให้นายจ้าง</p></div></div><div class="apply-job">${safe(currentJob.title)} · ${safe(currentJob.companyName)}</div><div class="review-box"><div class="review-row"><b>ชื่อ-นามสกุล</b><div>${safe(d.candidateName)}</div></div><div class="review-row"><b>เบอร์โทร</b><div>${safe(d.phone)}</div></div><div class="review-row"><b>อีเมล</b><div>${safe(d.email)}</div></div><div class="review-row"><b>อายุ</b><div>${safe(d.age)} ปี</div></div><div class="review-row"><b>ประสบการณ์</b><div>${safe(d.experience)}</div></div><div class="review-row"><b>การศึกษา</b><div>${safe(d.education)}</div></div></div><div class="apply-note">หลังส่งใบสมัคร กรุณาส่ง Resume ไปที่ <b>${safe(currentJob.contactEmail||"อีเมลของนายจ้าง")}</b></div><div class="apply-actions"><button class="btn ghost" id="editApplication" type="button">กลับไปแก้ไข</button><button class="btn primary" id="confirmApplication" type="button">ยืนยันสมัครงาน</button></div>`;
 $("#editApplication").onclick=openApplication;$("#confirmApplication").onclick=()=>submitApplication(d);
}

async function submitApplication(d){const u=auth.currentUser;if(!u)return;const id=`${currentJob.id}_${u.uid}`;try{await setDoc(doc(db,"applications",id),{jobId:currentJob.id,jobTitle:currentJob.title||"",companyId:currentJob.employerId,companyName:currentJob.companyName||"",employerEmail:currentJob.contactEmail||"",candidateId:u.uid,candidateName:d.candidateName,phone:d.phone,email:d.email,age:Number(d.age)||0,experience:d.experience,education:d.education,status:"submitted",createdAt:serverTimestamp(),updatedAt:serverTimestamp()});dialog.close();toast("สมัครงานสำเร็จ ส่งข้อมูลให้นายจ้างแล้ว");if(currentJob.contactEmail){setTimeout(()=>{if(confirm(`สมัครสำเร็จ\n\nต้องการเปิดอีเมลเพื่อส่ง Resume ไปที่ ${currentJob.contactEmail} หรือไม่?`))location.href=`mailto:${encodeURIComponent(currentJob.contactEmail)}?subject=${encodeURIComponent("Resume สมัครงานตำแหน่ง "+currentJob.title)}`},300)}}catch(e){toast((e?.code||"").includes("permission-denied")?"ส่งใบสมัครไม่ได้ กรุณาตรวจสอบ Firestore Rules":"ส่งใบสมัครไม่สำเร็จ กรุณาลองใหม่")}}

document.addEventListener("click",e=>{const view=e.target.closest?.("[data-view]");if(view?.dataset.view)currentJobId=view.dataset.view;const apply=e.target.closest?.("#applyBtn");if(apply){e.preventDefault();e.stopImmediatePropagation();openApplication()}},true);

function ensureApplicantPanel(){let p=$("#applicantPanel");if(p)return p;const dash=$("#employerDashboard");if(!dash)return null;p=document.createElement("div");p.id="applicantPanel";p.className="applicant-panel hidden";p.innerHTML='<div class="section-head"><div><span class="kicker light">ผู้สมัคร</span><h2>ผู้สมัครในตำแหน่งงานของคุณ</h2></div></div><p id="applicantMessage" style="color:#bae6fd"></p><div id="applicantList" class="applicant-list"></div>';dash.appendChild(p);return p}

function statusOptions(current){const opts=[['submitted','ส่งใบสมัครแล้ว'],['viewed','เปิดดูแล้ว'],['interview','นัดสัมภาษณ์'],['passed','ผ่าน'],['rejected','ไม่ผ่าน']];return opts.map(([v,l])=>`<option value="${v}" ${current===v?'selected':''}>${l}</option>`).join("")}
function watchApplications(u){if(stopApps){stopApps();stopApps=null}const panel=ensureApplicantPanel();if(!panel)return;panel.classList.remove("hidden");const msg=$("#applicantMessage"),list=$("#applicantList");msg.textContent="กำลังโหลดผู้สมัคร…";stopApps=onSnapshot(query(collection(db,"applications"),where("companyId","==",u.uid)),snap=>{const rows=snap.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0));msg.textContent=rows.length?`ผู้สมัครทั้งหมด ${rows.length} รายการ`:"ยังไม่มีผู้สมัคร";list.innerHTML=rows.map(a=>`<article class="applicant-card"><div class="applicant-card-head"><div><h3>${safe(a.candidateName)}</h3><div class="applicant-job">สมัคร: ${safe(a.jobTitle)} · ${safe(a.companyName)}</div></div><span class="badge">${dateText(a.createdAt)}</span></div><div class="applicant-info"><div><span>เบอร์โทร</span><br><b>${safe(a.phone||'-')}</b></div><div><span>อีเมล</span><br><b>${safe(a.email||'-')}</b></div><div><span>อายุ</span><br><b>${safe(a.age||'-')} ปี</b></div><div><span>ประสบการณ์</span><br><b>${safe(a.experience||'-')}</b></div><div><span>การศึกษา</span><br><b>${safe(a.education||'-')}</b></div><div><span>วันที่สมัคร</span><br><b>${dateText(a.createdAt)}</b></div></div><div class="applicant-status"><b>สถานะ:</b><select data-app-status="${a.id}">${statusOptions(a.status)}</select>${a.email?`<a class="resume-mail" href="mailto:${safe(a.email)}?subject=${encodeURIComponent('ขอ Resume สำหรับตำแหน่ง '+(a.jobTitle||''))}">✉ ขอ Resume ทางอีเมล</a>`:''}</div></article>`).join("");document.querySelectorAll('[data-app-status]').forEach(s=>s.onchange=async()=>{try{await updateDoc(doc(db,"applications",s.dataset.appStatus),{status:s.value,updatedAt:serverTimestamp()});toast("อัปเดตสถานะผู้สมัครแล้ว")}catch(e){toast("อัปเดตสถานะไม่สำเร็จ")}})},e=>{msg.textContent="โหลดผู้สมัครไม่สำเร็จ";console.error(e)})}

onAuthStateChanged(auth,async u=>{if(stopApps){stopApps();stopApps=null}const p=ensureApplicantPanel();if(!u){p?.classList.add("hidden");return}const prof=await userProfile();if(prof?.role==="employer"&&prof?.status!=="suspended")watchApplications(u);else p?.classList.add("hidden")});
